default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || 5  %>
  database: <%= ENV['PGDATABASE'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV["PGHOST"] %>
  reconnect: true

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default
  database: market_back_test

production:
  <<: *default
